export const BOOK_CATEGORIES = {
    featured: [
        'What to Read',
        'Summer Reading',
        'Used Books',
        'New Books',
        'Trending Titles',
        'Shelf Steals®',
        'Book Clubs',
        'Banned Books',
        'Adaptations',
        'Textbooks',
        'Rewards',
        'Gifts',
        'Deals',
    ],
    genres: [
        'Arts & Architecture',
        'Biography & Memoir',
        'Body, Mind, & Spirit',
        'Business',
        'Children\'s',
        'Computer & Technology',
        'Cookbooks & Wine',
        'Crafts & Hobbies',
        'Education',
        'Family & Relationships',
        'Fiction',
        'Health & Fitness',
        'History',
        'Home & Garden',
        'Horror',
        'Manga & Graphic Novels',
        'Medical & Nursing',
        'Mystery & Thrillers',
        'Non-Fiction',
        'Poetry',
        'Political Science',
        'Psychology',
        'Religion',
        'Romance',
        'Science Fiction',
        'Self Help',
        'Social Science',
        'Sports & Recreation',
        'Travel',
        'True Crime',
        'Young Adult',
    ]
} as const;

// This type will automatically update when categories are added/removed
export type BookCategory = typeof BOOK_CATEGORIES[keyof typeof BOOK_CATEGORIES][number];
